version: '3.7'

services:

  redis:
    image: redis:latest
    restart: always

  admin:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379
      - DEBUG=${DEBUG}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: /bin/bash -c 'python manage.py migrate;python manage.py runserver 0.0.0.0:8003'


  bot:
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - admin
    environment:
      - REDIS_URL=redis://redis:6379
      - DEBUG=${DEBUG}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: /bin/bash -c 'python manage.py startbot'

  db:
    image: postgres:14
    restart: always
    ports:
      - "54323:5432"
    volumes:
      - ${PWD}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - admin
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}-
      - DEBUG=${DEBUG}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: /bin/bash -c 'python manage.py rqworker high default low'
